# Generated by Django 5.1.2 on 2024-10-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_articulo', models.CharField(max_length=50)),
                ('des_articulo', models.CharField(max_length=100)),
                ('can_articulo', models.IntegerField()),
                ('pre_articulo', models.FloatField()),
                ('tip_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorias')),
            ],
        ),
    ]
