# Generated by Django 5.1.2 on 2024-10-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_transaccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_articulo', models.CharField(max_length=60)),
                ('des_articulo', models.CharField(max_length=100)),
                ('can_articulo', models.IntegerField()),
                ('pre_articulo', models.FloatField()),
                ('cat_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.IntegerField()),
                ('can_transaccion', models.IntegerField()),
                ('fec_transaccion', models.DateField()),
                ('tip_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipotransaccion')),
            ],
        ),
    ]
